[package]
name = "testing"
version = "0.1.0"
edition = "2021"


# [features]
# a_new = ["t_new"]
# a_old = ["t_old"]

[dependencies]
analyser = { path = "../analyser", features = ["a_old"] }
#dep = { path = "../dep_new", optional = true }
#dep = { path = "../dep_old", optional = true }
